# Generated by Django 3.2.9 on 2021-12-16 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20211216_1928'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='sex',
            field=models.CharField(default='', max_length=100, verbose_name='Название статьи'),
        ),
    ]
