# Generated by Django 3.2.9 on 2021-12-16 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_profile_sex'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='push',
            field=models.BooleanField(default='False', verbose_name='Уведомления на почту'),
        ),
    ]
