# Generated by Django 3.2.9 on 2021-12-17 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_profile_push'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='push',
            field=models.BooleanField(default='True', verbose_name='Уведомления на почту'),
        ),
    ]
