# Generated by Django 3.2.9 on 2021-12-16 12:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20211209_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='news',
            name='title',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='Название статьи'),
        ),
    ]
