# Generated by Django 3.2.9 on 2022-01-06 23:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0010_auto_20220107_0232'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comment',
            old_name='title_id',
            new_name='title',
        ),
        migrations.RenameField(
            model_name='comment',
            old_name='user_id',
            new_name='user',
        ),
    ]
